### ISSUE TITLE
NameError: name 'SubprocVecEnv' is not defined

### ISSUE THREAD

**Issue by matteomolino** [harry0731/freqtrade-gym#2]
Hi
Thanks very much for your work. I get an error when I run deep_rl.py. Here I paste it: (I run it on Ubuntu 18.04.5, Python 3.6, Tensorflow 1.14 )
python deep_rl.py
/home/mycomp/freqtrade/.env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/frequi/freqtrade/.env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/frequi/freqtrade/.env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/frequi/freqtrade/.env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:496: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/frequi/freqtrade/.env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:497: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/frequi/freqtrade/.env/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:502: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "deep_rl.py", line 21, in <module>
    env = SubprocVecEnv([lambda: TradingEnv(config)]*12)
NameError: name 'SubprocVecEnv' is not defined

**Comment by harry0731** [comment]
I have updated the deep_rl.py example and removed the SubprocVecEnv.
If you want to use SubprocVecEnv you can import if from stable_baselines.
`from stable_baselines.common.vec_env import SubprocVecEnv`
The SubprocVecEnv is for creating a multiprocess vectorized wrapper for multiple environments.
You can learn more about it in [here](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html#subprocvecenv).
