### ISSUE TITLE
Impossible to load Strategy 'IndicatorforRLFull'

### ISSUE THREAD

**Issue by matteomolino** [harry0731/freqtrade-gym#3]
Hi
First of all thanks very much for your support. I'm using your updated files and once I run the the code "python deep_rl.py" I get this error. I copied the strategy "IndicatorforRLFull" in freqtrade/user_data/strategies but it seems that it doesn't work. An idea why this happens? 
Thanks a million 🥇 

File "deep_rl.py", line 33, in <module>
    env = TradingEnv(config)
  File "/home/frequi/freqtrade/freqtradegym.py", line 36, in __init__
    self.strategy = StrategyResolver.load_strategy(config)
  File "/home/frequi/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 47, in load_strategy
    extra_dir=config.get('strategy_path'))
  File "/home/frequi/freqtrade/freqtrade/resolvers/strategy_resolver.py", line 192, in _load_strategy
    f"Impossible to load Strategy '{strategy_name}'. This class does not exist "
freqtrade.exceptions.OperationalException: Impossible to load Strategy 'IndicatorforRLFull'. This class does not exist or contains Python code errors.

**Comment by harry0731** [comment]
I have updated the deep_rl.py variable.
I use this gym to do a lot of experiments.
So the variables  are messy.
Sorry for that.

Feel free to open another issue if you encounter other issues.
And thank a million 🥇 too for using my project!
