### ISSUE TITLE
ImportError: DLL load failed while importing MPI: 

### ISSUE THREAD

**Issue by TekpreXyz** [harry0731/freqtrade-gym#8]
File "C:\Users\Kit\PycharmProjects\Freqconda\freqtrade\venv\lib\site-packages\stable_baselines\ddpg\ddpg.py", line 12, in <module>
    from mpi4py import MPI
ImportError: DLL load failed while importing MPI: Impossibile trovare il modulo specificato.

**Comment by TekpreXyz** [comment]
i solved installing this
https://docs.microsoft.com/en-us/message-passing-interface/microsoft-mpi

**Comment by harry0731** [comment]
Thank you for solving this.
I haven't try it on windows environments.
